server:
  port: 9002
spring:
  application:
    name: demo-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka
zuul:
  ignored-services: demo-scms-hystrix-dept
  routes:
    atguigu.serviceId: demo-scms-hystrix-dept
    atguigu.path: /springcloud-demo/**
  prefix: /total


